### ISSUE TITLE
ssr

### ISSUE THREAD

**Issue by boyfromhell** [connorabbas/primevue-breeze-inertia#18]
Hi.
 Nice project. 
I tried to make it work with ssr,
 but I can't get it to work,
 I get this error
``` bash
Starting SSR server on port 13714
Inertia SSR server started.
 ReferenceError: localStorage is not defined
at file:///var/www/html/bootstrap/ssr/assets/ToggleThemeButton-CEwuF5ZS.js:3:26
at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
 at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
at async j (file:///var/www/html/node_modules/@inertiajs/vue3/dist/index.esm.js:1:5861)
at async Server.<anonymous> (file:///var/www/html/node_modules/@inertiajs/core/dist/server.esm.js:1:527)
```

**Comment by connorabbas** [comment]
Thanks for the interest in the project, I just whipped up a quick working example on a separate [SSR branch:](https://github.com/connorabbas/primevue-breeze-inertia/compare/master...feature/ssr) that fixes the client side issues you are facing (localStorage is a browser only object). This should provide a good starting point for you.

The implementation on this new ssr branch works, but could definitely use some improvements. More specifically getting the PrimeVue theme css to load server side, and having the theme toggle have a better UX without requiring a full page reload (related issues). 

I'm going to close this issue, and open a new one related to the SSR PrimeVue styling 👍
